### ISSUE TITLE
Is this library available without npm and typescript?

### ISSUE THREAD

**Issue by rebootcode** [erikvullings/mithril-materialized#11]

**Comment by erikvullings** [comment]
@rebootcode All npm packages can be found on unpkg, for example, go to [release 0.16.2](https://unpkg.com/browse/mithril-materialized@0.16.2/dist/). There, you will find `index.*.js` files, all generated with `rollup` via [microbundle](https://github.com/developit/microbundle):

- [index.js](https://unpkg.com/mithril-materialized@0.16.2/dist/index.js): CommonJS/Node bundle
- [index.esm.js](https://unpkg.com/mithril-materialized@0.16.2/dist/index.esm.js): ESM module bundle
- [index.umd.js](https://unpkg.com/mithril-materialized@0.16.2/dist/index.umd.js): UMD module bundle
