### ISSUE TITLE
Type 'unknown' does not satisfy the constraint 'Lifecycle<ISelectOptions, unknown>'.

### ISSUE THREAD

**Issue by imanabu** [erikvullings/mithril-materialized#5]
Using TS 3.5.2 and when I compile I get the following when using the TextInput field

       m(TextInput, {
                    label: "First Name",
                    value: firstName,
                }),

node_modules/mithril-materialized/dist/layout-form-generator.d.ts:62:240 - error TS2344: Type 'unknown' does not satisfy the constraint 'Lifecycle<ISelectOptions, unknown>'.

I can get around this issue by manually replacing "unknown" to "any" but should this be kept as "any"?  Is there anything I should do so that unknown will work?

**Comment by erikvullings** [comment]
@imanabu Unfortunately, I cannot reproduce this issue, and the error message is actually related to the `LayoutForm` component that I use in the `Kanban` component, so I have no idea what is going on. Can you run the example project (in the packages/example folder)? 

Please re-open this issue if the problem persists with the latest version.
