### ISSUE TITLE
NumberInput doesn't support float input

### ISSUE THREAD

**Issue by DrManac** [erikvullings/mithril-materialized#9]
Similar issue is discussed at https://stackoverflow.com/questions/19011861/is-there-a-float-input-type-in-html5
Easy fix is to include input attribute **step** support.

```
mithril-materialized/packages/lib/src/utils.ts
...
const inputAttributes = [
  'min',
  'max',
  'minLength',
  'maxLength',
  'rows',
  'cols',
  'placeholder',
  'autocomplete',
  'pattern',
  'readOnly',
];
```

**Comment by erikvullings** [comment]
Thanks, good point. Will include it in the next release!
